import { CircularProgress } from "@material-ui/core";
import { getAuth } from "@store/actions";
import Head from 'next/head';
import React, { useContext, useEffect, useLayoutEffect, useState } from 'react';
import { APIResponse, User } from "types";
import { saveLocalstorage } from "@store/helper";
import Header from "./Header";
import Footer from "./HomeFooter";
import Sidebar from "./SideBard";
import { AppContext } from "../pages/_app";
import { actionCreator } from "@store/reducer";

interface LayoutProps {
    head?: string;
}

const DashboardLayout: React.FC<LayoutProps> = ({ head, children }) => {
    const context = useContext(AppContext),
        [data, setData] = useState<boolean>(false);

    useEffect(() => {
        const getUserAuth = async () => {
            const data = await getAuth();
            if (data) {
                const result = data.data as unknown as { token: string, user: User; };
                //set user in the context
                context.dispatch({
                    type: actionCreator.SET_USER,
                    payload: result.user
                });
                //set token in the context
                context.dispatch({
                    type: actionCreator.SET_TOKEN,
                    payload: result.token
                });
                if (window) {
                    saveLocalstorage(result.token, result.user);
                }
                setData(true);
            }
        };
        getUserAuth();
    }, [getAuth]);

    return (
        <>
            <Head>
                <title>Simba | Dashboard {head ? `| ${head}` : ''} </title>
                <meta name="description" content="Generated by create next app" />
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
                <meta name="description" content="Simba test application" />
                <meta name="keywords" content="simba test, next js, javascript, emmanuel popoola, eclipse" />
                <meta name="author" content="eclipse_cmd" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="/assets/css/dashlite.css?ver=2.9.1" />
                <link rel="stylesheet" href="/assets/css/theme.css?ver=2.9.1" />
            </Head>
            <div className="nk-app-root">
                {
                    data ?
                        (
                            <div className="nk-main">
                                <Sidebar />
                                <div className="nk-wrap position-relative padding-bottom-65">
                                    <Header />
                                    {children}
                                    <div className="float-footer">
                                        <Footer />
                                    </div>
                                </div>
                            </div>
                        )
                        :
                        (
                            <span className="btn-loader-icon loader-ring" style={{ backgroundColor: "#f5f6fa" }}><CircularProgress size={24} style={{ color: "#000000" }} /></span>
                        )
                }

            </div>
            <script src="/assets/js/bundle.js?ver=2.9.1"></script>
            <script src="/assets/js/scripts.js?ver=2.9.1"></script>
        </>
    );
};

export default DashboardLayout;