import Head from 'next/head';
import React from 'react';
import Footer from './HomeFooter';
import Header from './Header';

interface LayoutProps {
    head?: string;
}

const Layout: React.FC<LayoutProps> = ({ head, children }) => {
    return (
        <>
            <Head>
                <title>Simba Exchange {head ? `| ${head}` : ''} </title>
                <meta name="description" content="Generated by create next app" />
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
                <meta name="description" content="Simba test application" />
                <meta name="keywords" content="simba test, next js, javascript, emmanuel popoola, eclipse" />
                <meta name="author" content="eclipse_cmd" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="/assets/css/dashlite.css?ver=2.9.1" />
                <link id="skin-default" rel="stylesheet" href="/assets/css/theme.css?ver=2.9.1" />
            </Head>
            <div className="nk-app-root">
                {children}
            </div>
        </>
    );
};


export default Layout;