import Head from 'next/head'
import React from 'react'
import Footer from './Footer'
import Header from './Header'

interface LayoutProps {
    head?: string
}

const Layout: React.FC<LayoutProps> = ({ head, children }) => {
    return (
        <>
            <Head>
                <title>Simba Exchange {head ? `| ${head}` : ''} </title>
                <meta name="description" content="Generated by create next app" />
                <meta charSet="utf-8" />
                <meta name="description" content="Simba test application" />
                <meta name="keywords" content="simba test, next js, javascript, emmanuel popoola, eclipse" />
                <meta name="author" content="eclipse_cmd" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="theme-color" content="#FCB42D" />
                <link rel="preload" href="/assets/js/vendors/uikit.min.js" as="script" />
                <link rel="preload" href="/assets/css/vendors/uikit.min.css" as="style" />
                <link rel="preload" href="/assets/css/style.css" as="style" />
                <link rel="preload" href="/assets/fonts/fa-brands-400.woff2" as="font" type="font/woff2" crossOrigin={"true"} />
                <link rel="preload" href="/assets/fonts/fa-solid-900.woff2" as="font" type="font/woff2" crossOrigin={"true"} />
                <link rel="preload" href="/assets/fonts/archivo-v9-latin-regular.woff2" as="font" type="font/woff2" crossOrigin={"true"} />
                <link rel="preload" href="/assets/fonts/archivo-v9-latin-300.woff2" as="font" type="font/woff2" crossOrigin={"true"} />
                <link rel="preload" href="/assets/fonts/archivo-v9-latin-700.woff2" as="font" type="font/woff2" crossOrigin={"true"} />
                <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
                <link rel="stylesheet" href="/assets/css/vendors/uikit.min.css" />
                <link rel="stylesheet" href="/assets/css/style.css"></link>
            </Head>

            {/* <Header /> */}
            <main>
                {children}
            </main>

            {/* <Footer /> */}
        </>
    )
}


export default Layout